name: manager_on_duty
description: "A new Flutter project."
publish_to: "none"
version: 1.2.3+2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  http: ^1.2.2
  google_fonts: ^4.0.4
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  intl: ^0.19.0
  url_launcher: ^6.3.1

  badges: ^3.1.2
  #timelines_plus: ^1.0.3

  flutter_animate: ^4.4.0
  expansion_tile_card: ^3.0.0
  connectivity_plus: ^5.0.2
  flutter_cache_manager: ^3.3.1

  pdf: ^3.11.1
  path: ^1.8.3
  path_provider: ^2.1.4
  open_filex: ^4.7.0
  permission_handler: ^11.3.1
  # sqflite: ^2.3.3+1
  printing: ^5.13.1
  package_info_plus: ^8.1.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
